---
driver:
  name: lxd_cli
  ipv4: 10.0.3.5
  ip_gateway: 10.0.3.1
#  stop_instead_of_destroy: true
  config: 
    limits.memory: 1G
    boot.autostart: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
- name: proxy
  run_list:
  - recipe[lxd_polipo]
